version: "1.0"

services:
  nginx:
    container_name: 'nginx'
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80 #wystawione porty 80 dla app oraz 9001 dla dprawdzania statusu nginxa
      - 9001:9001
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #kopiujemy plik konfiguracyjny nginxa do kontenera
    networks:
      - app
    restart: always

  app:
    container_name: 'app'
    build:
      context: .
      dockerfile: app/Dockerfile
    networks:
      - app
    restart: always


networks:
  app:
    driver: bridge